### ISSUE TITLE
External target support, configurable "/target"

### ISSUE THREAD

**Issue by mdhomer** [persona-id/squid-check#9]
Hi, I was looking to use this project for determining the health of our squid-proxy upstream. 

The difference with our setup is this proxy is connected via a physical connection to another network. And we need our Azure LB healthchecks to be tied to requests to a particular endpoint hosted externally.

What I was hoping to achieve was using this binary as such:

Where google.com would be resolved and the request sent to determine if the proxy is healthy.
`/opt/squid-check/squid-check -target-address "https://google.com"`

I think with your current code, the `target-address` will only be translated as a request to:
```
		resp, err := s.proxyClient.Get(fmt.Sprintf("http://%s/target", flags.targetAddress))
```
https://github.com/persona-id/squid-check/blob/main/main.go#L73C4-L73C50

Which would be to:
`https://google.com/target` which in our case isn't served.

Are you open to allowing "targetAddress" to be modified to remove `/target` suffix. Or if I provide another override for this so I can set it to "/".

I'm thinking either:
`/opt/squid-check/squid-check -target-address "https://google.com/"`
or
`/opt/squid-check/squid-check -target-address "https://google.com" -target-suffix "/"` (this would be backwards compatible).

**Comment by mdhomer** [comment]
Hi @derektamsen, I've created a pull-request with some changes to support this request - https://github.com/persona-id/squid-check/pull/10

**Comment by kuzmik** [comment]
Hello @mdhomer, I merged the PR (thank you again), but I will need @derektamsen to teach me how to cut a release for this repo. 

We will get it released by EOD Monday (Pacific time)

**Comment by derektamsen** [comment]
@mdhomer Thanks for the pull request! Thanks @kuzmik for the review! I created release [v0.1.0](https://github.com/persona-id/squid-check/releases/tag/v0.1.0) with your changes. Their is also an [updated container tag](https://github.com/persona-id/squid-check/pkgs/container/squid-check/239884666?tag=v0.1.0) built from the release.
